---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.4.*
  - 2.5.*
  - 2.6.*
  - 2.7.*
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 6.0" STRICT_VARIABLES=yes
matrix:
  exclude:
    - rvm: 2.7.*
      env: PUPPET_GEM_VERSION="~> 5.0"
    - rvm: 2.4.*
      env: PUPPET_GEM_VERSION="~> 6.0"