---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 6.0" STRICT_VARIABLES=yes